### PR TITLE
Single command bus

### PR DESCRIPTION
**Pull request by sagikazarmark**
This is the same as #13, but rebased #17

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@rosstuck IIRC we agreed on this one, can I merge it?

**Comment by rosstuck** [comment]
I think neither of us are completely happy with the wrapping solution but in the spirit of today's dual-mode STH being accepted...it shall be so! :dancer: :smiley: 

The only other comment I'd have is maybe giving clearer names to Receiver and PreventLoopReceiver, which we've both suggested before. We could name them after the use cases they address but that's hard to describe. QueuedFromSameBusReceiver and QueuedFromSeparateBusReceiver is a bit odd.

We can always pick that up in another PR though and we still need docs on the main branch when it's all settled. Either way, good work and hustle, man! :smile:

**Comment by sagikazarmark** [comment]
@rosstuck dat names. :stuck_out_tongue_winking_eye:  SameBusReceiver and SeparateBusReceiver?

I think we can stick to this solution now. Honestly I was thinking about making the queueable commands mutable because that would definitely make some things easier from the implementation side, from the usage side it would make users cry. So one day, when an AI examines our code, maybe it could come up with a better solution.

**Comment by sagikazarmark** [comment]
Receiver/WrappingReceiver?

Actually the name doesn't really matter if we can explain it. We can't make it simple and self-describing, because someone have to know the

**Comment by rosstuck** [comment]
I prefer the previous names, wrapping is an internal implementation detail.

**Comment by sagikazarmark** [comment]
SameBusReceiver and SeparateBusReceiver?

**Comment by rosstuck** [comment]
Yup

**Pull request merged**
