### PR TITLE
Use Bernard's consumer

### PR DESCRIPTION
**Pull request by sagikazarmark**
I opened a separate issue for this. We talked about this several times, now I realise it might be the right choice to simply remove the custom implementation of the Consumer.

Some reasons why I chose to have a custom implementation:
- Bernard uses Symfony EventDispatcher, while League packages usually uses League\Event (like CommandEvents plugin itself) Using both is a bit weird.
- Bernard consumer has a quite ugly option handling logic, which consumes more memory (based on my quick benchmarks) than the event logic I created.

The reason I created this PR: I agree with @rosstuck, Tactician is rather a router in this context. So my plan is to remove consumer logic (or export it to a generic package, which uses the same router logic as the core one does).

### CODE REVIEW

**Comment by rosstuck** [comment]
Yeah, I think this makes a much thinner integration point. We're only really relying on Bernard's public API and the Router interface, both of which are small and hopefully unlikely to change. And it better suits Tactician's role here.

This does mean we probably need to make it explicit in the docs that the Queue middleware likely goes to the top of the stack, I reckon.

This also encourages moving some of the plugins like wait and throttle up the chain to Bernard core where they can benefit the most users.

As for the other reasons:
- I think folks would understand about the different event dispatchers. Bernard uses Symfony, Tactician uses League, it's scoped by library that way.
- I think it means we don't require CommandEvents for the Bernard integration anymore (depending on the plugins). CommandEvents is still useful in its own right of course. We can always add more variants in the CommandEvents plugin if people really want them (one for League, one for ZF, one for Symfony, etc). Admittedly, I'd rather have an emitter PSR...
- I don't know enough about Bernard's architecture to have any thoughts on the options handling. It could be that it consumes more memory in the short term but stays static over the long term, which is vital for worker scripts. Regardless, we'd be in a better situation to benefit from their upstream improvements this way.

So, I think this is definitely the way to go. :+1: fo' sho'.

**Comment by sagikazarmark** [comment]
Well, I am pretty sure the API will change, but the router architecture
will probably remain the same.

I've already removed the command events dependency.

Anything to add? If not, I will add docs to the website, merge the PRs and
prepare the rename.

**Comment by rosstuck** [comment]
Sounds good! I think pre-1.0 we ought to look at some of the QueueableCommand interface and the decision making there (maybe splitting the decision to queue into a separate interface, etc) but it's easier to do that later on and once everything is merged.

**Comment by sagikazarmark** [comment]
Separate interface what?? ;)

**Comment by sagikazarmark** [comment]
@rosstuck Can you explain me (possibly in a separate issue) what you were trying to say about QueueableCommand, because I don't get it.

**Comment by rosstuck** [comment]
@sagikazarmark I was referring to if this line should be made configurable: https://github.com/thephpleague/tactician-bernard-queueing/blob/master/src/QueueMiddleware.php#L34 In other words, if we should let a separate object return a true/false if the command should be queued. That would make the decision "to queue or not to queue" configurable.

That said, it's really thin now and maybe we should just wait to see if there's user demand for such a feature before adding it now. Otherwise, it's just featureitis. 

Two other points:
- I really like how slim the library's become, nice work!
- Dumb question but is there anything stopping an infinite loop from occurring here? It seems like you'd queue a command, it'd go into the queue, the Router unpacks it and then drops it back into the command bus where it gets queued again? Aside from passing a separate Command Bus to the workers, am I missing something? :sweat_smile:

**Comment by sagikazarmark** [comment]
Well, I am not sure that it could work. The problem is that you have to make sure that the Queue can serialize your command. This means that your object should rather be persistent in being able to queued or not queued. However this is something that we could think about later.
- Thanks!
- Yeah, it is a dumb question. :stuck_out_tongue_closed_eyes: First of all the consumer itself IS an infinite loop, but there are built-it mechanisms which let you have some control over it: maximum number of commands, maximum time, etc. Secondly, yeah, the consumer runs separately from the application, thus it should be an entirely different Command Bus. If someone is stupid enough to use the same Command Bus setup, then he/she deserves the consequences. :smile: But I think it is clear in the docs: in the first case you pass a QueueMiddleware, in the second one I left the space for middlewares empty with a comment about custom middlewares.

**Pull request merged**
